# Generated by Django 5.2.14 on 2026-05-27 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0006_add_dot_percentage_to_invoice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoiceline',
            options={'ordering': ['volgorde', 'created_at'], 'verbose_name': 'Factuur Regel', 'verbose_name_plural': 'Factuur Regels'},
        ),
    ]
