# Generated by Django 5.2.17 on 2026-09-05 12:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_land'),
        ('core', '0021_administratie_bedrijfsgegevens'),
        ('invoicing', '0008_add_administratie_to_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactuurWizardBedrijf',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('btw_percentage', models.DecimalField(decimal_places=2, default=21, max_digits=5, verbose_name='BTW %')),
                ('betaaltermijn_dagen', models.PositiveSmallIntegerField(default=30, help_text='De vervaldatum wordt de factuurdatum plus dit aantal dagen.', verbose_name='Betaaltermijn (dagen)')),
                ('actief', models.BooleanField(default=True, help_text='Alleen actieve bedrijven verschijnen in de wizard.', verbose_name='Actief')),
                ('volgorde', models.PositiveIntegerField(default=0, verbose_name='Volgorde')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('administratie', models.ForeignKey(blank=True, help_text='Bepaalt de factuurnummering en wie de factuur mag inzien.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factuurwizard_bedrijven', to='core.administratie', verbose_name='Administratie')),
                ('bedrijf', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='factuurwizard', to='companies.company', verbose_name='Bedrijf')),
                ('template', models.ForeignKey(help_text='De template die automatisch wordt gebruikt bij dit bedrijf.', on_delete=django.db.models.deletion.PROTECT, related_name='factuurwizard_bedrijven', to='invoicing.invoicetemplate', verbose_name='Factuur template')),
            ],
            options={
                'verbose_name': 'Factuurwizard bedrijf',
                'verbose_name_plural': 'Factuurwizard bedrijven',
                'ordering': ['volgorde', 'bedrijf__naam'],
            },
        ),
        migrations.CreateModel(
            name='FactuurWizardDienst',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ritnummer', models.CharField(help_text='Het routenummer zoals het in de vloot staat.', max_length=50, verbose_name='Routenummer')),
                ('omschrijving', models.CharField(blank=True, help_text='Optionele toelichting, bijvoorbeeld het type wagen.', max_length=200, verbose_name='Toelichting')),
                ('actief', models.BooleanField(default=True, verbose_name='Actief')),
                ('volgorde', models.PositiveIntegerField(default=0, verbose_name='Volgorde')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diensten', to='invoicing.factuurwizardbedrijf', verbose_name='Bedrijf')),
            ],
            options={
                'verbose_name': 'Factuurwizard dienst',
                'verbose_name_plural': 'Factuurwizard diensten',
                'ordering': ['volgorde', 'ritnummer'],
                'constraints': [models.UniqueConstraint(fields=('config', 'ritnummer'), name='uniek_ritnummer_per_wizardbedrijf')],
            },
        ),
    ]
