# Generated by Django 5.2.13 on 2026-04-21 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_tachographsynclog'),
    ]

    operations = [
        migrations.CreateModel(
            name='TachographArchiveEntry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='Datum')),
                ('object_id', models.CharField(max_length=100, verbose_name='Object ID')),
                ('vehicle_name', models.CharField(blank=True, max_length=255, verbose_name='Voertuig')),
                ('vehicle_make', models.CharField(blank=True, max_length=100, verbose_name='Merk')),
                ('vehicle_model', models.CharField(blank=True, max_length=100, verbose_name='Model')),
                ('plate_number', models.CharField(blank=True, max_length=100, verbose_name='Kenteken')),
                ('first_start', models.DateTimeField(blank=True, null=True, verbose_name='Eerste start')),
                ('last_end', models.DateTimeField(blank=True, null=True, verbose_name='Laatste einde')),
                ('first_km', models.FloatField(default=0, verbose_name='Start KM')),
                ('last_km', models.FloatField(default=0, verbose_name='Eind KM')),
                ('total_km', models.FloatField(default=0, verbose_name='Totaal KM')),
                ('total_duration_seconds', models.PositiveIntegerField(default=0, verbose_name='Totale duur (s)')),
                ('total_hours', models.FloatField(default=0, verbose_name='Totale uren')),
                ('total_hours_display', models.CharField(blank=True, max_length=20, verbose_name='Totale uren (weergave)')),
                ('overtime_hours', models.FloatField(default=0, verbose_name='Overuren')),
                ('overtime_display', models.CharField(blank=True, max_length=20, null=True, verbose_name='Overuren (weergave)')),
                ('has_overtime', models.BooleanField(default=False, verbose_name='Heeft overuren')),
                ('overtime_calculation', models.JSONField(blank=True, null=True, verbose_name='Overuren berekening')),
                ('drivers', models.JSONField(blank=True, default=list, verbose_name='Chauffeurs')),
                ('trips', models.JSONField(blank=True, default=list, verbose_name='Ritten')),
                ('trip_count', models.PositiveIntegerField(default=0, verbose_name='Aantal ritten')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tachograaf Archief Regel',
                'verbose_name_plural': 'Tachograaf Archief Regels',
                'ordering': ['-date', 'vehicle_name'],
                'indexes': [models.Index(fields=['date'], name='tracking_ta_date_b65646_idx'), models.Index(fields=['date', 'plate_number'], name='tracking_ta_date_5c453b_idx'), models.Index(fields=['date', 'vehicle_name'], name='tracking_ta_date_2cb6e8_idx')],
                'unique_together': {('date', 'object_id')},
            },
        ),
    ]
