# Generated by Django 5.2.17 on 2026-09-23 19:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_tachographarchiveentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='RadiusSyncLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(unique=True, verbose_name='Datum')),
                ('journeys_synced', models.PositiveIntegerField(default=0, verbose_name='Ritten gesynchroniseerd')),
                ('journeys_created', models.PositiveIntegerField(default=0, verbose_name='Nieuwe ritten')),
                ('vehicles_seen', models.PositiveIntegerField(default=0, verbose_name='Voertuigen gezien')),
                ('errors', models.TextField(blank=True, verbose_name='Fouten')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Radius Sync Log',
                'verbose_name_plural': 'Radius Sync Logs',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='RadiusJourney',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('service_id', models.CharField(max_length=64, verbose_name='Service ID')),
                ('plate_number', models.CharField(blank=True, max_length=20, verbose_name='Kenteken')),
                ('driver_name', models.CharField(blank=True, max_length=150, verbose_name='Chauffeur')),
                ('date', models.DateField(help_text='Lokale datum waarop de rit begon.', verbose_name='Datum')),
                ('start_time', models.DateTimeField(verbose_name='Starttijd')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Eindtijd')),
                ('start_latitude', models.FloatField(blank=True, null=True, verbose_name='Start breedtegraad')),
                ('start_longitude', models.FloatField(blank=True, null=True, verbose_name='Start lengtegraad')),
                ('end_latitude', models.FloatField(blank=True, null=True, verbose_name='Eind breedtegraad')),
                ('end_longitude', models.FloatField(blank=True, null=True, verbose_name='Eind lengtegraad')),
                ('start_address', models.CharField(blank=True, max_length=255, verbose_name='Startadres')),
                ('start_city', models.CharField(blank=True, max_length=120, verbose_name='Startplaats')),
                ('start_country', models.CharField(blank=True, max_length=100, verbose_name='Startland')),
                ('end_address', models.CharField(blank=True, max_length=255, verbose_name='Eindadres')),
                ('end_city', models.CharField(blank=True, max_length=120, verbose_name='Eindplaats')),
                ('end_country', models.CharField(blank=True, max_length=100, verbose_name='Eindland')),
                ('distance_km', models.FloatField(default=0, verbose_name='Afstand (km)')),
                ('duration_seconds', models.PositiveIntegerField(default=0, verbose_name='Duur (s)')),
                ('customer_id', models.CharField(blank=True, max_length=32, verbose_name='Radius klant-id')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Radius Rit',
                'verbose_name_plural': 'Radius Ritten',
                'ordering': ['-start_time', 'plate_number'],
                'indexes': [models.Index(fields=['date'], name='tracking_ra_date_172a1e_idx'), models.Index(fields=['date', 'plate_number'], name='tracking_ra_date_f07283_idx'), models.Index(fields=['plate_number', '-start_time'], name='tracking_ra_plate_n_8755e9_idx')],
                'unique_together': {('service_id', 'start_time')},
            },
        ),
    ]
