# Generated by Django 5.2.14 on 2026-05-21 19:30

import apps.core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_add_email_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailprofile',
            name='oauth_client_secret',
            field=apps.core.models.EncryptedCharField(blank=True, max_length=512, verbose_name='OAuth Client Secret'),
        ),
        migrations.AlterField(
            model_name='emailprofile',
            name='smtp_password',
            field=apps.core.models.EncryptedCharField(blank=True, max_length=512, verbose_name='SMTP Wachtwoord'),
        ),
    ]
