# Generated by Django 5.2.17 on 2026-09-23 18:22

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_administratie_bedrijfsgegevens'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='radius_api_token',
            field=apps.core.models.EncryptedCharField(blank=True, help_text='Refresh token uit het Radius Velocity Portal (Account > API integratie).', max_length=512, verbose_name='Radius API Token'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='radius_start_datum',
            field=models.DateField(blank=True, help_text='Vanaf welke datum Radius rit- en GPS-gegevens opgehaald moeten worden.', null=True, verbose_name='Radius startdatum'),
        ),
    ]
