# Generated by Django 5.2.15 on 2026-07-03 12:34

import apps.loadlist.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=120)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=apps.loadlist.models.loadlist_photo_upload_path)),
                ('start_address', models.CharField(blank=True, default='', help_text='Vertrekpunt (depot). Wordt gebruikt als startpunt voor de route.', max_length=250)),
                ('start_lat', models.FloatField(blank=True, null=True)),
                ('start_lng', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('uploaded', 'Geüpload'), ('parsing', 'Bezig met inlezen'), ('parsed', 'Ingelezen'), ('optimizing', 'Bezig met optimaliseren'), ('optimized', 'Geoptimaliseerd'), ('error', 'Fout')], default='uploaded', max_length=20)),
                ('status_message', models.CharField(blank=True, default='', max_length=500)),
                ('raw_ocr_text', models.TextField(blank=True, default='')),
                ('extraction_provider', models.CharField(blank=True, default='', max_length=40)),
                ('total_distance_m', models.PositiveIntegerField(blank=True, null=True)),
                ('total_duration_s', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loadlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Laadlijst',
                'verbose_name_plural': 'Laadlijsten',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoadStop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_sequence', models.PositiveIntegerField(default=0)),
                ('delivery_sequence', models.PositiveIntegerField(blank=True, null=True)),
                ('load_sequence', models.PositiveIntegerField(blank=True, null=True)),
                ('address_raw', models.CharField(max_length=300)),
                ('address_formatted', models.CharField(blank=True, default='', max_length=300)),
                ('postcode', models.CharField(blank=True, default='', max_length=20)),
                ('city', models.CharField(blank=True, default='', max_length=120)),
                ('country', models.CharField(blank=True, default='', max_length=80)),
                ('reference', models.CharField(blank=True, default='', help_text='Ordernummer / referentie zoals op de lijst', max_length=80)),
                ('colli', models.PositiveIntegerField(blank=True, null=True)),
                ('pallets', models.PositiveIntegerField(blank=True, null=True)),
                ('weight_kg', models.FloatField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, default='', max_length=250)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('geocode_confidence', models.CharField(blank=True, default='', max_length=20)),
                ('geocode_error', models.CharField(blank=True, default='', max_length=200)),
                ('loadlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='loadlist.loadlist')),
            ],
            options={
                'verbose_name': 'Stop',
                'verbose_name_plural': 'Stops',
                'ordering': ['loadlist', 'original_sequence'],
            },
        ),
    ]
