# Generated by Django 5.2.15 on 2026-07-06 06:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoicing', '0008_add_administratie_to_invoice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TollingImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('rows_total', models.PositiveIntegerField(default=0)),
                ('rows_imported', models.PositiveIntegerField(default=0)),
                ('rows_duplicate', models.PositiveIntegerField(default=0)),
                ('rows_invalid', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tolling_import_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tolheffing import batch',
                'verbose_name_plural': 'Tolheffing import batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TollingEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_at', models.DateTimeField(verbose_name='Startdatum')),
                ('end_at', models.DateTimeField(verbose_name='Einddatum')),
                ('distance_km', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Afstand (km)')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Bedrag')),
                ('license_plate_raw', models.CharField(max_length=32, verbose_name='Kenteken (bron)')),
                ('license_plate_normalized', models.CharField(db_index=True, max_length=32, verbose_name='Kenteken (genormaliseerd)')),
                ('obu', models.CharField(blank=True, max_length=64, verbose_name='OBU')),
                ('invoiced_at', models.DateTimeField(blank=True, null=True, verbose_name='Gefactureerd op')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tolling_events', to='invoicing.invoiceline')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='tolling.tollingimportbatch')),
            ],
            options={
                'verbose_name': 'Tolheffing event',
                'verbose_name_plural': 'Tolheffing events',
                'ordering': ['-start_at'],
                'indexes': [models.Index(fields=['license_plate_normalized', 'start_at'], name='tolling_tol_license_6f3786_idx'), models.Index(fields=['invoiced_at'], name='tolling_tol_invoice_c1cef6_idx')],
                'constraints': [models.UniqueConstraint(fields=('start_at', 'end_at', 'license_plate_normalized', 'amount', 'obu'), name='tolling_event_unique_fingerprint')],
            },
        ),
    ]
