# Generated by Django 5.2.17 on 2026-08-29 20:27

import re

import django.db.models.deletion
from django.db import migrations, models


def _normalize_plate(value):
    if not value:
        return ''
    return re.sub(r'[^A-Z0-9]', '', value.upper())


def backfill_ritnummer(apps, schema_editor):
    """Vul de momentopname voor bestaande events met de huidige vloot.

    Verder terug reconstrueren kan niet: het ritnummer van vóór deze
    migratie is nergens vastgelegd. Vanaf nu blijft de historie wel intact.
    """
    TollingEvent = apps.get_model('tolling', 'TollingEvent')
    Vehicle = apps.get_model('fleet', 'Vehicle')

    lookup = {}
    for v in Vehicle.objects.select_related('bedrijf').order_by('actief', 'created_at'):
        key = _normalize_plate(v.kenteken)
        if key:
            lookup[key] = v

    if not lookup:
        return

    updates = []
    qs = TollingEvent.objects.all().only(
        'id', 'license_plate_normalized', 'vehicle_id', 'ritnummer', 'bedrijf_id'
    )
    for event in qs.iterator(chunk_size=2000):
        vehicle = lookup.get(event.license_plate_normalized)
        if not vehicle:
            continue
        event.vehicle_id = vehicle.id
        event.ritnummer = (vehicle.ritnummer or '').strip()
        event.bedrijf_id = vehicle.bedrijf_id
        updates.append(event)
        if len(updates) >= 2000:
            TollingEvent.objects.bulk_update(updates, ['vehicle_id', 'ritnummer', 'bedrijf_id'])
            updates = []
    if updates:
        TollingEvent.objects.bulk_update(updates, ['vehicle_id', 'ritnummer', 'bedrijf_id'])


def noop(apps, schema_editor):
    """Terugdraaien hoeft niets te doen; de kolommen verdwijnen toch."""


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_land'),
        ('fleet', '0005_remove_old_kenteken_unique_index'),
        ('invoicing', '0008_add_administratie_to_invoice'),
        ('tolling', '0003_admin_invoiced'),
    ]

    operations = [
        # De indexnamen liepen uit de pas met de modeldefinitie. In sommige
        # databases dragen ze al de nieuwe naam, daarom hernoemen we met
        # IF EXISTS en houden we de migratiestatus apart bij.
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='ALTER INDEX IF EXISTS tolling_pri_user_id_datum_idx '
                        'RENAME TO tolling_pri_user_id_0e46e5_idx;',
                    reverse_sql='ALTER INDEX IF EXISTS tolling_pri_user_id_0e46e5_idx '
                                'RENAME TO tolling_pri_user_id_datum_idx;',
                ),
                migrations.RunSQL(
                    sql='ALTER INDEX IF EXISTS tolling_pri_plate_datum_idx '
                        'RENAME TO tolling_pri_license_4cc013_idx;',
                    reverse_sql='ALTER INDEX IF EXISTS tolling_pri_license_4cc013_idx '
                                'RENAME TO tolling_pri_plate_datum_idx;',
                ),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name='privatetollregistration',
                    new_name='tolling_pri_user_id_0e46e5_idx',
                    old_name='tolling_pri_user_id_datum_idx',
                ),
                migrations.RenameIndex(
                    model_name='privatetollregistration',
                    new_name='tolling_pri_license_4cc013_idx',
                    old_name='tolling_pri_plate_datum_idx',
                ),
            ],
        ),
        migrations.AddField(
            model_name='tollingevent',
            name='bedrijf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tolling_events', to='companies.company', verbose_name='Bedrijf'),
        ),
        migrations.AddField(
            model_name='tollingevent',
            name='ritnummer',
            field=models.CharField(blank=True, db_index=True, help_text='Ritnummer van de wagen op het moment van importeren.', max_length=50, verbose_name='Ritnummer'),
        ),
        migrations.AddField(
            model_name='tollingevent',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tolling_events', to='fleet.vehicle', verbose_name='Voertuig'),
        ),
        migrations.AddIndex(
            model_name='tollingevent',
            index=models.Index(fields=['license_plate_normalized', 'ritnummer'], name='tolling_tol_license_151616_idx'),
        ),
        migrations.RunPython(backfill_ritnummer, noop),
    ]
