# Generated by Django 5.2.17 on 2026-08-30 08:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tolling', '0004_tollingevent_ritnummer_snapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RitnummerCorrectie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('license_plate_normalized', models.CharField(db_index=True, max_length=32, verbose_name='Kenteken (genormaliseerd)')),
                ('license_plate_raw', models.CharField(blank=True, max_length=32, verbose_name='Kenteken')),
                ('van', models.DateField(verbose_name='Van')),
                ('tot', models.DateField(verbose_name='Tot en met')),
                ('van_ritnummer', models.CharField(blank=True, help_text='Leeg betekent: alle ritnummers in de periode.', max_length=50, null=True, verbose_name='Alleen dit oude ritnummer')),
                ('naar_ritnummer', models.CharField(max_length=50, verbose_name='Nieuw ritnummer')),
                ('inclusief_gefactureerd', models.BooleanField(default=False, verbose_name='Ook gefactureerde regels')),
                ('aantal', models.PositiveIntegerField(default=0, verbose_name='Aantal regels')),
                ('oude_waarden', models.JSONField(default=dict, verbose_name='Oude ritnummers per regel')),
                ('uitgevoerd_op', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Uitgevoerd op')),
                ('teruggedraaid_op', models.DateTimeField(blank=True, null=True, verbose_name='Teruggedraaid op')),
                ('teruggedraaid_aantal', models.PositiveIntegerField(default=0, verbose_name='Aantal teruggezette regels')),
                ('teruggedraaid_door', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ritnummer_correcties_teruggedraaid', to=settings.AUTH_USER_MODEL, verbose_name='Teruggedraaid door')),
                ('uitgevoerd_door', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ritnummer_correcties', to=settings.AUTH_USER_MODEL, verbose_name='Uitgevoerd door')),
            ],
            options={
                'verbose_name': 'Ritnummercorrectie',
                'verbose_name_plural': 'Ritnummercorrecties',
                'ordering': ['-uitgevoerd_op'],
                'indexes': [models.Index(fields=['license_plate_normalized', '-uitgevoerd_op'], name='tolling_rit_license_1ce567_idx')],
            },
        ),
    ]
