# Generated by Django 5.2.17 on 2026-09-08 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tolling', '0005_ritnummercorrectie'),
    ]

    operations = [
        migrations.AddField(
            model_name='tollingimportbatch',
            name='rows_zero_amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
