# Generated by Django 5.2.17 on 2026-09-22 20:09

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_land'),
        ('fleet', '0007_vehicle_bedrijf_periodes'),
        ('tolling', '0006_tollingimportbatch_rows_zero_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TolAfrekening',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bestandsnaam', models.CharField(blank=True, max_length=255, verbose_name='Bestandsnaam')),
                ('bestand', models.FileField(blank=True, null=True, upload_to='tolling/afrekeningen/%Y/%m/', verbose_name='Bestand')),
                ('bonnummer', models.CharField(blank=True, max_length=64, verbose_name='Bonnummer')),
                ('klantnummer', models.CharField(blank=True, max_length=64, verbose_name='Klantnummer')),
                ('factuurdatum', models.DateField(blank=True, null=True, verbose_name='Factuurdatum')),
                ('periode_van', models.DateField(verbose_name='Periode van')),
                ('periode_tot', models.DateField(verbose_name='Periode tot en met')),
                ('werktijd_van', models.TimeField(default=datetime.time(6, 0), verbose_name='Werktijd van')),
                ('werktijd_tot', models.TimeField(default=datetime.time(18, 0), verbose_name='Werktijd tot')),
                ('totaal_netto', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Totaal netto')),
                ('totaal_maut', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Totaal tolvergoeding')),
                ('waarschuwingen', models.JSONField(blank=True, default=list, verbose_name='Waarschuwingen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bedrijf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tol_afrekeningen', to='companies.company', verbose_name='Opdrachtgever')),
                ('geuploaded_door', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tol_afrekeningen', to=settings.AUTH_USER_MODEL, verbose_name='Geupload door')),
            ],
            options={
                'verbose_name': 'Tolafrekening opdrachtgever',
                'verbose_name_plural': 'Tolafrekeningen opdrachtgever',
                'ordering': ['-periode_van', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TolAfrekeningRegel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('regelnummer', models.CharField(blank=True, max_length=8, verbose_name='Regelnummer')),
                ('voertuig_label', models.CharField(max_length=64, verbose_name='Voertuig op afrekening')),
                ('ritnummer', models.CharField(db_index=True, max_length=50, verbose_name='Ritnummer')),
                ('inzetdagen', models.PositiveIntegerField(default=0, verbose_name='Inzetdagen')),
                ('ritten', models.PositiveIntegerField(default=0, verbose_name='Aantal ritten')),
                ('kilometers', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Kilometers')),
                ('netto_bedrag', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Netto bedrag')),
                ('dagforfait', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Dagforfait')),
                ('brandstoftoeslag', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Brandstoftoeslag')),
                ('maut_ontvangen', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Ontvangen tolvergoeding')),
                ('maut_gevonden', models.BooleanField(default=False, verbose_name='Tolvergoeding op afrekening')),
                ('kenteken', models.CharField(blank=True, max_length=64, verbose_name='Kenteken')),
                ('kentekens', models.JSONField(blank=True, default=list, verbose_name='Kentekens (genormaliseerd)')),
                ('koppeling', models.CharField(choices=[('gekoppeld', 'Gekoppeld'), ('geen_voertuig', 'Ritnummer onbekend'), ('meerdere', 'Meerdere voertuigen')], default='geen_voertuig', max_length=20, verbose_name='Koppeling')),
                ('dagen', models.JSONField(blank=True, default=list, verbose_name='Dagregels')),
                ('afrekening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regels', to='tolling.tolafrekening')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tol_afrekening_regels', to='fleet.vehicle', verbose_name='Voertuig')),
            ],
            options={
                'verbose_name': 'Tolafrekening regel',
                'verbose_name_plural': 'Tolafrekening regels',
                'ordering': ['afrekening', 'regelnummer'],
            },
        ),
        migrations.AddIndex(
            model_name='tolafrekening',
            index=models.Index(fields=['periode_van', 'periode_tot'], name='tolling_tol_periode_9caace_idx'),
        ),
        migrations.AddConstraint(
            model_name='tolafrekening',
            constraint=models.UniqueConstraint(condition=models.Q(('bonnummer__gt', '')), fields=('bonnummer', 'periode_van', 'periode_tot'), name='tol_afrekening_unieke_bon'),
        ),
        migrations.AddConstraint(
            model_name='tolafrekeningregel',
            constraint=models.UniqueConstraint(fields=('afrekening', 'voertuig_label'), name='tol_afrekening_regel_uniek_voertuig'),
        ),
    ]
