# Generated by Django 5.2.14 on 2026-05-31 16:52

import apps.core.models
import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0018_appsettings_email_signature_image'),
        ('fleet', '0005_remove_old_kenteken_unique_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PakmiddelenAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=64, verbose_name='Actie')),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pakmiddelen Audit Log',
                'verbose_name_plural': 'Pakmiddelen Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PakmiddelenCheckResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('check_date', models.DateField(db_index=True, verbose_name='Controledatum')),
                ('ritnummer', models.CharField(db_index=True, max_length=50, verbose_name='Ritnummer')),
                ('has_bon', models.BooleanField(default=False, verbose_name='Pakmiddelen teruggavebon ontvangen')),
                ('matched_subject', models.CharField(blank=True, max_length=500, verbose_name='Onderwerp')),
                ('mail_message_id', models.CharField(blank=True, max_length=255, verbose_name='Mail Message-ID')),
                ('mail_received_at', models.DateTimeField(blank=True, null=True, verbose_name='Mail ontvangen op')),
                ('notification_sent', models.BooleanField(default=False, verbose_name='Rapportmail verstuurd')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pakmiddelen Resultaat',
                'verbose_name_plural': 'Pakmiddelen Resultaten',
                'ordering': ['-check_date', 'ritnummer'],
                'constraints': [models.UniqueConstraint(fields=('check_date', 'ritnummer'), name='unique_pakmiddelen_result_per_day')],
            },
        ),
        migrations.CreateModel(
            name='PakmiddelenConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('imap_host', models.CharField(blank=True, max_length=255, verbose_name='IMAP Host')),
                ('imap_port', models.PositiveIntegerField(default=993, verbose_name='IMAP Poort')),
                ('imap_use_ssl', models.BooleanField(default=True, verbose_name='Gebruik SSL/TLS')),
                ('imap_username', models.CharField(blank=True, max_length=255, verbose_name='IMAP Gebruikersnaam')),
                ('imap_password', apps.core.models.EncryptedCharField(blank=True, max_length=512, verbose_name='IMAP Wachtwoord')),
                ('imap_folder', models.CharField(default='INBOX', help_text='Bijvoorbeeld INBOX, INBOX/Pakmiddelen, etc.', max_length=255, verbose_name='IMAP Map')),
                ('subject_template', models.CharField(default='Pakmiddelen teruggavebon {ritnummer}', help_text='Gebruik {ritnummer} als placeholder voor het ritnummer.', max_length=500, verbose_name='Onderwerp template')),
                ('mark_as_read', models.BooleanField(default=True, help_text='Verwerkte mails worden in de mailbox als gelezen gemarkeerd.', verbose_name='Mails als gelezen markeren')),
                ('enabled', models.BooleanField(default=False, verbose_name='Actief')),
                ('schedule_time', models.TimeField(default=datetime.time(18, 0), help_text='Tijdstip waarop de mailbox dagelijks wordt uitgelezen en de rapportmail wordt verstuurd.', verbose_name='Tijdstip dagelijkse controle')),
                ('period_days', models.PositiveIntegerField(default=1, help_text='Aantal dagen terug waarvoor mails worden uitgelezen vanaf vandaag.', verbose_name='Periode (dagen)')),
                ('period_from_date', models.DateField(blank=True, help_text='Vaste startdatum. Indien gezet wordt deze gebruikt in plaats van Periode (dagen).', null=True, verbose_name='Vanaf datum (optioneel)')),
                ('notification_recipients', models.JSONField(blank=True, default=list, help_text='Lijst van e-mailadressen die het dagelijks overzicht ontvangen.', verbose_name='Ontvangers rapportmail')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='Laatste run')),
                ('last_run_status', models.CharField(blank=True, max_length=50, verbose_name='Laatste status')),
                ('last_run_message', models.TextField(blank=True, verbose_name='Laatste run melding')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_email_profile', models.ForeignKey(blank=True, help_text='Optioneel SMTP-profiel. Standaard wordt het standaard profiel gebruikt.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pakmiddelen_configs', to='core.emailprofile', verbose_name='Verzend-profiel (SMTP)')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Laatst gewijzigd door')),
            ],
            options={
                'verbose_name': 'Pakmiddelen Configuratie',
                'verbose_name_plural': 'Pakmiddelen Configuratie',
            },
        ),
        migrations.CreateModel(
            name='PakmiddelenRitnummerSelection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ritnummer', models.CharField(max_length=50, verbose_name='Ritnummer')),
                ('actief', models.BooleanField(default=True, verbose_name='Actief')),
                ('notitie', models.CharField(blank=True, max_length=255, verbose_name='Notitie')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pakmiddelen_selections', to='fleet.vehicle', verbose_name='Voertuig')),
            ],
            options={
                'verbose_name': 'Pakmiddelen Ritnummer',
                'verbose_name_plural': 'Pakmiddelen Ritnummers',
                'ordering': ['ritnummer'],
                'constraints': [models.UniqueConstraint(fields=('ritnummer',), name='unique_pakmiddelen_ritnummer')],
            },
        ),
    ]
