# Generated by Django 5.2.14 on 2026-05-31 17:10

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pakmiddelen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pakmiddelenconfig',
            name='graph_client_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Application (client) ID'),
        ),
        migrations.AddField(
            model_name='pakmiddelenconfig',
            name='graph_client_secret',
            field=apps.core.models.EncryptedCharField(blank=True, max_length=1024, verbose_name='Client Secret'),
        ),
        migrations.AddField(
            model_name='pakmiddelenconfig',
            name='graph_client_secret_expires_at',
            field=models.DateField(blank=True, help_text='Datum waarop het client secret verloopt. Herinneringen worden 30/14/7 dagen vooraf gestuurd.', null=True, verbose_name='Vervaldatum client secret'),
        ),
        migrations.AddField(
            model_name='pakmiddelenconfig',
            name='graph_folder',
            field=models.CharField(blank=True, default='Inbox', help_text='Naam van de well-known folder of het folder-id (Inbox, SentItems, etc.).', max_length=255, verbose_name='Mailmap'),
        ),
        migrations.AddField(
            model_name='pakmiddelenconfig',
            name='graph_mailbox',
            field=models.CharField(blank=True, help_text='Het postvak dat uitgelezen wordt (bijv. info@bedrijf.nl). Vereist Mail.Read app-permission.', max_length=255, verbose_name='Mailbox (UPN of object-id)'),
        ),
        migrations.AddField(
            model_name='pakmiddelenconfig',
            name='graph_secret_reminders_sent',
            field=models.JSONField(blank=True, default=list, help_text='Lijst van reeds verstuurde herinneringen (30/14/7) voor de huidige vervaldatum.', verbose_name='Verzonden secret-herinneringen'),
        ),
        migrations.AddField(
            model_name='pakmiddelenconfig',
            name='graph_tenant_id',
            field=models.CharField(blank=True, help_text='Directory (tenant) ID uit Azure / Entra ID.', max_length=255, verbose_name='Microsoft Tenant ID'),
        ),
        migrations.AddField(
            model_name='pakmiddelenconfig',
            name='provider',
            field=models.CharField(choices=[('imap', 'IMAP'), ('graph', 'Microsoft Graph (OAuth2)')], default='imap', max_length=16, verbose_name='Mailprovider'),
        ),
    ]
