# Generated by Django 5.2.14 on 2026-05-31 19:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pakmiddelen', '0002_pakmiddelenconfig_graph_client_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PakmiddelenMailLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Verzonden op')),
                ('mail_type', models.CharField(choices=[('daily_report', 'Dagelijks rapport'), ('overview', 'Overzicht'), ('test', 'Testmail'), ('secret_expiry', 'Secret-expiratie herinnering')], db_index=True, default='daily_report', max_length=32, verbose_name='Type mail')),
                ('recipients', models.JSONField(blank=True, default=list, verbose_name='Ontvangers')),
                ('subject', models.CharField(blank=True, max_length=500, verbose_name='Onderwerp')),
                ('success', models.BooleanField(db_index=True, default=False, verbose_name='Succesvol')),
                ('message', models.TextField(blank=True, verbose_name='Melding / fout')),
                ('related_date', models.DateField(blank=True, null=True, verbose_name='Gerelateerde datum')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Gestart door')),
            ],
            options={
                'verbose_name': 'Pakmiddelen Mail Log',
                'verbose_name_plural': 'Pakmiddelen Mail Logs',
                'ordering': ['-sent_at'],
            },
        ),
    ]
