# Generated by Django 5.2.17 on 2026-09-17 17:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0007_vehicle_bedrijf_periodes'),
        ('maintenance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ADRRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('route', models.CharField(blank=True, help_text='Ritnummer/route van het voertuig. Leeg = automatisch van de wagen overnemen.', max_length=50, verbose_name='Route')),
                ('has_adr', models.BooleanField(default=True, verbose_name='ADR')),
                ('case_sealed', models.BooleanField(default=False, verbose_name='ADR koffer verzegeld')),
                ('inspection_date', models.DateField(verbose_name='Controle uitgevoerd op')),
                ('next_inspection_date', models.DateField(verbose_name='Volgende controle op')),
                ('notify_extra_emails', models.JSONField(blank=True, default=list, help_text='Losse adressen die naast de gekozen gebruikers een herinnering krijgen.', verbose_name='Extra e-mailadressen')),
                ('remarks', models.TextField(blank=True, verbose_name='Opmerkingen')),
                ('last_reminder_sent_on', models.DateField(blank=True, help_text='Datum waarop voor het laatst een herinnering is verstuurd.', null=True, verbose_name='Laatste herinnering')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_adr_records', to=settings.AUTH_USER_MODEL, verbose_name='Aangemaakt door')),
                ('notify_users', models.ManyToManyField(blank=True, related_name='adr_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Notificatie naar')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adr_records', to='fleet.vehicle', verbose_name='Voertuig')),
            ],
            options={
                'verbose_name': 'ADR Controle',
                'verbose_name_plural': 'ADR Controles',
                'ordering': ['next_inspection_date'],
                'indexes': [models.Index(fields=['next_inspection_date'], name='maintenance_next_in_590789_idx')],
            },
        ),
    ]
