# Generated by Django 5.2.17 on 2026-09-23 08:37

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_administratie_bedrijfsgegevens'),
        ('fleet', '0007_vehicle_bedrijf_periodes'),
        ('maintenance', '0003_adrsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FireExtinguisherSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('send_hour', models.PositiveSmallIntegerField(default=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)], verbose_name='Verzenduur')),
                ('send_minute', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(59)], verbose_name='Verzendminuut')),
                ('default_notify_extra_emails', models.JSONField(blank=True, default=list, verbose_name='Standaard extra e-mailadressen')),
                ('last_run_on', models.DateField(blank=True, null=True, verbose_name='Laatste run op')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_notify_users', models.ManyToManyField(blank=True, related_name='fire_extinguisher_default_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Standaard ontvangers')),
                ('email_profile', models.ForeignKey(blank=True, help_text='Leeg = de algemene SMTP-instellingen gebruiken.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fire_extinguisher_settings', to='core.emailprofile', verbose_name='Verzend-account')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_fire_extinguisher_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Brandblusser Instellingen',
                'verbose_name_plural': 'Brandblusser Instellingen',
            },
        ),
        migrations.CreateModel(
            name='FireExtinguisherRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('route', models.CharField(blank=True, help_text='Ritnummer/route van het voertuig. Leeg = automatisch van de wagen overnemen.', max_length=50, verbose_name='Route')),
                ('volgnummer', models.PositiveSmallIntegerField(default=1, help_text='Volgnummer van deze blusser op de wagen.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Blusser nr.')),
                ('positie', models.CharField(blank=True, help_text='Bijvoorbeeld cabine, chassis links of achterzijde.', max_length=100, verbose_name='Plaats op de wagen')),
                ('serienummer', models.CharField(blank=True, max_length=64, verbose_name='Serienummer')),
                ('inspection_date', models.DateField(verbose_name='Gekeurd op')),
                ('next_inspection_date', models.DateField(verbose_name='Vervaldatum')),
                ('notify_extra_emails', models.JSONField(blank=True, default=list, help_text='Losse adressen die naast de gekozen gebruikers een herinnering krijgen.', verbose_name='Extra e-mailadressen')),
                ('remarks', models.TextField(blank=True, verbose_name='Opmerkingen')),
                ('last_reminder_sent_on', models.DateField(blank=True, help_text='Datum waarop voor het laatst een herinnering is verstuurd.', null=True, verbose_name='Laatste herinnering')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_fire_extinguishers', to=settings.AUTH_USER_MODEL, verbose_name='Aangemaakt door')),
                ('notify_users', models.ManyToManyField(blank=True, related_name='fire_extinguisher_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Notificatie naar')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fire_extinguishers', to='fleet.vehicle', verbose_name='Voertuig')),
            ],
            options={
                'verbose_name': 'Brandblusser',
                'verbose_name_plural': 'Brandblussers',
                'ordering': ['next_inspection_date', 'vehicle__kenteken', 'volgnummer'],
                'indexes': [models.Index(fields=['next_inspection_date'], name='maintenance_next_in_9d52d2_idx'), models.Index(fields=['vehicle', 'volgnummer'], name='maintenance_vehicle_5892a4_idx')],
            },
        ),
    ]
