# Generated by Django 5.2.17 on 2026-09-23 12:58

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_administratie_bedrijfsgegevens'),
        ('maintenance', '0004_fireextinguishersettings_fireextinguisherrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='apkrecord',
            name='last_reminder_sent_on',
            field=models.DateField(blank=True, help_text='Datum waarop voor het laatst een herinnering is verstuurd.', null=True, verbose_name='Laatste herinnering'),
        ),
        migrations.AddField(
            model_name='apkrecord',
            name='notify_extra_emails',
            field=models.JSONField(blank=True, default=list, help_text='Losse adressen die naast de gekozen gebruikers een herinnering krijgen.', verbose_name='Extra e-mailadressen'),
        ),
        migrations.AddField(
            model_name='apkrecord',
            name='notify_users',
            field=models.ManyToManyField(blank=True, related_name='apk_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Notificatie naar'),
        ),
        migrations.CreateModel(
            name='APKSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('send_hour', models.PositiveSmallIntegerField(default=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)], verbose_name='Verzenduur')),
                ('send_minute', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(59)], verbose_name='Verzendminuut')),
                ('default_notify_extra_emails', models.JSONField(blank=True, default=list, verbose_name='Standaard extra e-mailadressen')),
                ('last_run_on', models.DateField(blank=True, null=True, verbose_name='Laatste run op')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_notify_users', models.ManyToManyField(blank=True, related_name='apk_default_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Standaard ontvangers')),
                ('email_profile', models.ForeignKey(blank=True, help_text='Leeg = de algemene SMTP-instellingen gebruiken.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apk_settings', to='core.emailprofile', verbose_name='Verzend-account')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_apk_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'APK Instellingen',
                'verbose_name_plural': 'APK Instellingen',
            },
        ),
    ]
