# Generated by Django 5.2.11 on 2026-03-02 09:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyMinimumHours',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('jaar', models.PositiveIntegerField(verbose_name='Jaar')),
                ('weeknummer', models.PositiveIntegerField(verbose_name='Weeknummer')),
                ('minimum_uren', models.DecimalField(decimal_places=2, default=40, max_digits=5, verbose_name='Minimale uren')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_minimum_hours', to=settings.AUTH_USER_MODEL, verbose_name='Gebruiker')),
            ],
            options={
                'verbose_name': 'Minimale weekuren',
                'verbose_name_plural': 'Minimale weekuren',
                'ordering': ['-jaar', '-weeknummer'],
                'unique_together': {('user', 'jaar', 'weeknummer')},
            },
        ),
    ]
