# Generated by Django 5.2.12 on 2026-03-12 14:47

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_vehicle_minimum_weken_per_jaar'),
        ('timetracking', '0002_weeklyminimumhours'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bestandsnaam', models.CharField(max_length=255, verbose_name='Bestandsnaam')),
                ('bestand', models.FileField(blank=True, null=True, upload_to='imports/uren/', verbose_name='Bestand')),
                ('totaal_rijen', models.PositiveIntegerField(default=0, verbose_name='Totaal rijen')),
                ('gekoppeld', models.PositiveIntegerField(default=0, verbose_name='Gekoppeld aan chauffeur')),
                ('niet_gekoppeld', models.PositiveIntegerField(default=0, verbose_name='Niet gekoppeld')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('geimporteerd_door', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_batches', to=settings.AUTH_USER_MODEL, verbose_name='Geïmporteerd door')),
            ],
            options={
                'verbose_name': 'Import Batch',
                'verbose_name_plural': 'Import Batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportedTimeEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weeknummer', models.PositiveIntegerField(verbose_name='Weeknummer')),
                ('periode', models.CharField(blank=True, default='', max_length=50, verbose_name='Periode')),
                ('datum', models.DateField(verbose_name='Datum')),
                ('ritlijst', models.CharField(blank=True, default='', max_length=100, verbose_name='Ritlijst')),
                ('kenteken_import', models.CharField(max_length=50, verbose_name='Kenteken (import)')),
                ('km', models.DecimalField(decimal_places=1, default=0, max_digits=10, verbose_name='KM')),
                ('uurtarief', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Uurtarief')),
                ('dot', models.CharField(blank=True, default='', max_length=50, verbose_name='DOT')),
                ('geplande_vertrektijd', models.TimeField(blank=True, null=True, verbose_name='Geplande vertrektijd')),
                ('ingelogd_bc', models.TimeField(blank=True, null=True, verbose_name='Ingelogd BC')),
                ('begintijd_rit', models.TimeField(blank=True, null=True, verbose_name='Begintijd rit')),
                ('eindtijd_rit', models.TimeField(blank=True, null=True, verbose_name='Eindtijd rit')),
                ('uren', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Uren')),
                ('pauze', models.DurationField(default=datetime.timedelta(0), verbose_name='Pauze')),
                ('netto_uren', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Netto uren')),
                ('uren_factuur', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Uren factuur')),
                ('factuur_bedrag', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Factuur bedrag')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='timetracking.importbatch', verbose_name='Import Batch')),
                ('gekoppeld_voertuig', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_entries', to='fleet.vehicle', verbose_name='Gekoppeld voertuig')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_time_entries', to=settings.AUTH_USER_MODEL, verbose_name='Gekoppelde gebruiker')),
            ],
            options={
                'verbose_name': 'Geïmporteerde urenregel',
                'verbose_name_plural': 'Geïmporteerde urenregels',
                'ordering': ['-datum', 'kenteken_import'],
            },
        ),
    ]
