# Generated by Django 5.2.15 on 2026-06-25 08:43

import apps.timetracking.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracking', '0006_timeentry_kilometerheffing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tolregistratie',
            name='bijlage',
            field=models.FileField(blank=True, null=True, upload_to=apps.timetracking.models.tol_bijlage_upload_path, verbose_name='Bijlage'),
        ),
        migrations.AlterField(
            model_name='tolregistratie',
            name='datum',
            field=models.DateField(blank=True, null=True, verbose_name='Datum'),
        ),
        migrations.AlterField(
            model_name='tolregistratie',
            name='kenteken',
            field=models.CharField(blank=True, max_length=20, verbose_name='Kenteken'),
        ),
        migrations.CreateModel(
            name='TolRit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ritnummer', models.CharField(max_length=50, verbose_name='Ritnummer')),
                ('volgorde', models.PositiveIntegerField(default=0, verbose_name='Volgorde')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tol_registratie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ritten', to='timetracking.tolregistratie', verbose_name='Tolregistratie')),
            ],
            options={
                'verbose_name': 'Tolrit',
                'verbose_name_plural': 'Tolritten',
                'ordering': ['volgorde', 'created_at'],
            },
        ),
    ]
