# Generated by Django 5.2.11 on 2026-03-02 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='minimum_weken_per_jaar',
            field=models.PositiveIntegerField(blank=True, help_text='Minimaal aantal weken dat dit voertuig per jaar moet draaien. Laat leeg om niet bij te houden.', null=True, verbose_name='Minimum weken per jaar'),
        ),
    ]
