# Generated by Django 5.2.12 on 2026-03-12 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_driver_minimum_uren_per_week'),
        ('fleet', '0002_vehicle_minimum_weken_per_jaar'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='voertuig',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chauffeurs', to='fleet.vehicle', verbose_name='Voertuig (Ritnummer)'),
        ),
    ]
