# Generated by Django 5.2.15 on 2026-06-22 12:23

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskReminderSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('daily_reminder_enabled', models.BooleanField(default=True, verbose_name='Dagelijkse herinnering aan')),
                ('daily_reminder_hour', models.PositiveSmallIntegerField(default=9, verbose_name='Uur dagelijkse herinnering (0-23)')),
                ('daily_reminder_minute', models.PositiveSmallIntegerField(default=0, verbose_name='Minuut dagelijkse herinnering (0-59)')),
                ('daily_reminder_weekdays', models.JSONField(blank=True, default=list, help_text='Lijst van weekdagen (0=maandag ... 6=zondag). Leeg = elke dag.', verbose_name='Weekdagen dagelijkse herinnering')),
                ('stale_reminder_enabled', models.BooleanField(default=True, verbose_name='Herinnering bij stilstand aan')),
                ('stale_after_days', models.PositiveSmallIntegerField(default=2, verbose_name='Aantal dagen stilstand voor herinnering')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Taken reminder-instellingen',
                'verbose_name_plural': 'Taken reminder-instellingen',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titel', models.CharField(max_length=255, verbose_name='Titel')),
                ('omschrijving', models.TextField(blank=True, verbose_name='Omschrijving')),
                ('status', models.CharField(choices=[('nieuw', 'Nieuw'), ('in_behandeling', 'In behandeling'), ('afgerond', 'Afgerond')], default='nieuw', max_length=20, verbose_name='Status')),
                ('prioriteit', models.CharField(choices=[('laag', 'Laag'), ('normaal', 'Normaal'), ('hoog', 'Hoog')], default='normaal', max_length=10, verbose_name='Prioriteit')),
                ('vervaldatum', models.DateField(blank=True, null=True, verbose_name='Vervaldatum')),
                ('status_changed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Status gewijzigd op')),
                ('last_activity_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Laatste activiteit op')),
                ('last_reminder_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Laatste reminder op')),
                ('afgerond_op', models.DateTimeField(blank=True, null=True, verbose_name='Afgerond op')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aangemaakt_door', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Aangemaakt door')),
                ('toegewezen_aan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Toegewezen aan')),
            ],
            options={
                'verbose_name': 'Taak',
                'verbose_name_plural': 'Taken',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actie', models.CharField(max_length=255, verbose_name='Actie')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='tasks.task')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Taakactiviteit',
                'verbose_name_plural': 'Taakactiviteiten',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tekst', models.TextField(verbose_name='Notitie')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_notes', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='tasks.task')),
            ],
            options={
                'verbose_name': 'Taaknotitie',
                'verbose_name_plural': 'Taaknotities',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['toegewezen_aan', 'status'], name='tasks_task_toegewe_afaab0_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['aangemaakt_door', 'status'], name='tasks_task_aangema_7c44fb_idx'),
        ),
    ]
