# Generated by Django 5.2.16 on 2026-07-15 20:04

import apps.documents.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Naam')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_folders', to=settings.AUTH_USER_MODEL, verbose_name='Aangemaakt door')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='documents.folder', verbose_name='Bovenliggende map')),
            ],
            options={
                'verbose_name': 'Map',
                'verbose_name_plural': 'Mappen',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FileEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Weergavenaam')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Originele bestandsnaam')),
                ('file', models.FileField(upload_to=apps.documents.models.file_entry_upload_path, verbose_name='Bestand')),
                ('size', models.PositiveBigIntegerField(default=0, verbose_name='Grootte (bytes)')),
                ('mime_type', models.CharField(blank=True, max_length=127, verbose_name='MIME-type')),
                ('extension', models.CharField(blank=True, max_length=16, verbose_name='Extensie')),
                ('content_text', models.TextField(blank=True, help_text='Uit het document geëxtraheerde tekst voor zoeken (pdf/docx/xlsx/csv/txt).', verbose_name='Geïndexeerde tekst')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_file_entries', to=settings.AUTH_USER_MODEL, verbose_name='Geüpload door')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='documents.folder', verbose_name='Map')),
            ],
            options={
                'verbose_name': 'Bestand',
                'verbose_name_plural': 'Bestanden',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FolderPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('can_edit', models.BooleanField(default=True, help_text='Bestanden uploaden/verwijderen en submappen aanmaken. Uit = alleen bekijken.', verbose_name='Mag wijzigen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='documents.folder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folder_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Map-toegang',
                'verbose_name_plural': 'Map-toegangen',
            },
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['parent'], name='documents_f_parent__c80268_idx'),
        ),
        migrations.AddConstraint(
            model_name='folder',
            constraint=models.UniqueConstraint(fields=('parent', 'name'), name='folder_unique_name_per_parent'),
        ),
        migrations.AddIndex(
            model_name='fileentry',
            index=models.Index(fields=['folder'], name='documents_f_folder__599547_idx'),
        ),
        migrations.AddIndex(
            model_name='fileentry',
            index=models.Index(fields=['extension'], name='documents_f_extensi_7cd35e_idx'),
        ),
        migrations.AddConstraint(
            model_name='folderpermission',
            constraint=models.UniqueConstraint(fields=('folder', 'user'), name='folder_permission_unique'),
        ),
    ]
