# Generated by Django 5.2.12 on 2026-03-29 17:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Titel')),
                ('report_type', models.CharField(choices=[('leave_overview_user', 'Verlof overzicht per gebruiker'), ('leave_balance_overview', 'Verlof saldo overzicht alle medewerkers'), ('leave_requests_overview', 'Verlofaanvragen overzicht'), ('trips_by_user', 'Alle ritten van een gebruiker'), ('trips_by_vehicle', 'Alle ritten van een voertuig (ritnummer)'), ('time_entries_summary', 'Urenregistratie samenvatting'), ('time_entries_by_user', 'Urenregistraties per gebruiker'), ('time_entries_by_week', 'Urenregistraties per week'), ('weekly_hours_summary', 'Wekelijkse uren samenvatting'), ('vehicle_overview', 'Voertuigen overzicht'), ('vehicle_maintenance', 'Onderhoud overzicht per voertuig'), ('driver_overview', 'Chauffeurs overzicht'), ('driver_activity', 'Activiteit per chauffeur'), ('invoice_overview', 'Facturen overzicht'), ('invoice_by_company', 'Facturen per bedrijf'), ('revenue_summary', 'Omzet samenvatting'), ('company_overview', 'Bedrijven overzicht'), ('maintenance_overview', 'Onderhoud overzicht'), ('apk_overview', 'APK overzicht'), ('planning_overview', 'Planning overzicht'), ('banking_transactions', 'Bank transacties overzicht'), ('spreadsheet_overview', 'Ritregistratie overzicht')], max_length=50, verbose_name='Rapport type')),
                ('parameters', models.JSONField(blank=True, default=dict, help_text='JSON object with query parameters (user_id, year, vehicle_id, date_from, date_to, etc.)', verbose_name='Parameters')),
                ('output_format', models.CharField(choices=[('screen', 'Scherm'), ('excel', 'Excel'), ('pdf', 'PDF'), ('all', 'Alle formaten')], default='all', max_length=10, verbose_name='Uitvoer formaat')),
                ('status', models.CharField(choices=[('pending', 'In wachtrij'), ('processing', 'Wordt verwerkt'), ('completed', 'Voltooid'), ('failed', 'Mislukt')], default='pending', max_length=20, verbose_name='Status')),
                ('result_data', models.JSONField(blank=True, null=True, verbose_name='Resultaat data')),
                ('excel_file', models.FileField(blank=True, null=True, upload_to='reports/excel/', verbose_name='Excel bestand')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='reports/pdf/', verbose_name='PDF bestand')),
                ('error_message', models.TextField(blank=True, verbose_name='Foutmelding')),
                ('row_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Aantal rijen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Aangemaakt op')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Bijgewerkt op')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Voltooid op')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_requests', to=settings.AUTH_USER_MODEL, verbose_name='Aangevraagd door')),
            ],
            options={
                'verbose_name': 'Rapport verzoek',
                'verbose_name_plural': 'Rapport verzoeken',
                'ordering': ['-created_at'],
            },
        ),
    ]
