# Generated by Django 5.2.17 on 2026-08-18 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportrequest",
            name="report_type",
            field=models.CharField(
                choices=[
                    ("leave_overview_user", "Verlof overzicht per gebruiker"),
                    (
                        "leave_balance_overview",
                        "Verlof saldo overzicht alle medewerkers",
                    ),
                    ("leave_requests_overview", "Verlofaanvragen overzicht"),
                    ("trips_by_user", "Alle ritten van een gebruiker"),
                    ("trips_by_vehicle", "Alle ritten van een voertuig (ritnummer)"),
                    ("time_entries_summary", "Urenregistratie samenvatting"),
                    ("time_entries_by_user", "Urenregistraties per gebruiker"),
                    ("time_entries_by_week", "Urenregistraties per week"),
                    ("weekly_hours_summary", "Wekelijkse uren samenvatting"),
                    ("imported_hours", "Geïmporteerde uren overzicht"),
                    ("vehicle_overview", "Voertuigen overzicht"),
                    ("vehicle_maintenance", "Onderhoud overzicht per voertuig"),
                    ("driver_overview", "Chauffeurs overzicht"),
                    ("driver_activity", "Activiteit per chauffeur"),
                    ("invoice_overview", "Facturen overzicht"),
                    ("invoice_by_company", "Facturen per bedrijf"),
                    ("revenue_summary", "Omzet samenvatting"),
                    ("company_overview", "Bedrijven overzicht"),
                    ("maintenance_overview", "Onderhoud overzicht"),
                    ("apk_overview", "APK overzicht"),
                    ("planning_overview", "Planning overzicht"),
                    ("banking_transactions", "Bank transacties overzicht"),
                    ("spreadsheet_overview", "Ritregistratie overzicht"),
                    ("vehicle_trips_by_date", "Ritnummers per voertuig per dag"),
                ],
                max_length=50,
                verbose_name="Rapport type",
            ),
        ),
    ]
