# Generated by Django 5.2.12 on 2026-04-02 19:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('vakantie', 'Vakantie'), ('overuren', 'Verlof overuren'), ('bijzonder_tandarts', 'Bijzonder verlof tandarts'), ('bijzonder_huisarts', 'Bijzonder verlof huisarts'), ('ziekteverzuim', 'Ziekteverzuim')], max_length=30, verbose_name='Type verlof'),
        ),
        migrations.CreateModel(
            name='PublicHoliday',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(unique=True, verbose_name='Datum')),
                ('name', models.CharField(max_length=100, verbose_name='Naam')),
                ('year', models.IntegerField(db_index=True, verbose_name='Jaar')),
            ],
            options={
                'verbose_name': 'Feestdag',
                'verbose_name_plural': 'Feestdagen',
                'ordering': ['date'],
            },
        ),
    ]
