# Generated by Django 5.2.12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_add_leave_reminder_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(
                choices=[
                    ('vakantie', 'Vakantie'),
                    ('overuren', 'Verlof overuren'),
                    ('bijzonder_tandarts', 'Bijzonder verlof tandarts'),
                    ('bijzonder_huisarts', 'Bijzonder verlof huisarts'),
                    ('ziekteverzuim', 'Ziekteverzuim'),
                    ('onbetaald', 'Onbetaald verlof'),
                ],
                max_length=30,
                verbose_name='Type verlof',
            ),
        ),
    ]
